name=SmartProsthesisShared
version=1.0.0
author=Abraham May, Hammer Elisheva, Yampolsky Avigail
maintainer=Abraham May
sentence=Shared variables and YAML parser for the Smart Prosthesis project.
paragraph=This library contains shared definitions for communications, parser data structures, and utilities.
category=Communication
url=
architectures=*
depends=ArduinoJson, YAMLDuino
